name: Container Workflow
# Define your inputs here.
inputs:
  who-to-greet:
    description: 'Who to greet'
    required: true
    default: 'World'
on:
  workflow_dispatch:

  
  # Define your outputs here.
  outputs:
    time:
      description: 'The time we greeted you'
  
  runs:
    using: docker
    image: Dockerfile
    args:
      - ${{ inputs.who-to-greet }}
