name: GitHub actions demo
on: 
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        type: environment
        required: true
  push:
    branches:
      - main
    paths-ignore:
      - './github/**'
  pull_request:
    branches:
      - main
    paths-ignore:
      - './github/**'
  schedule:
    - cron: '15 06 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Output the event name
      run: echo "The event that triggered this workflow is ${{ github.event_name }}"
    - name: Output the branch name
      run: echo "The current branch is ${{ github.ref_name }}"
