name: Run container action
on: [push]
workflow_dispatch: {} 
 push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run local action
      uses: ./hello-world-docker-action/action.yml
