name: Run container action
on: 
  push:
    branches:
      - main
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Run local action
      uses: ./hello-world-docker-action

    - name: Output
      run: echo "The time was ${{ steps.hello-action.outputs.time }} when the action said hello"
